### ISSUE TITLE
Watched movies by user

### ISSUE THREAD

**Issue by shapirogrill** [shapirogrill/movies_itinov#8]
A user should be able to notify if he has watched a movie or not and get them.

# TODO : 
- [x] Create a watched field in `UserReview`
- [x]  Create an endpoint to allow user to add / remove a watched field
- [ ] Create an endpoint to allow user to get all movies he has watched or not
- [ ] Unit Test all
